# ==================================================
# @file ~/.config/pip/pip.conf
# @brief pip package installation configuration
# ==================================================


[global]
require-virtualenv = true
